apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-green
spec:
  replicas: 0  # Initially zero
  selector:
    matchLabels:
      app: demo
      version: "2.0.0"
  template:
    metadata:
      labels:
        app: demo
        version: "2.0.0"
    spec:
      containers:
      - name: app
        image: nginx:1.26.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config
        configMap:
          name: app-v2-config