apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-blue
spec:
  replicas: 5
  selector:
    matchLabels:
      app: demo
      version: "1.0.0"
  template:
    metadata:
      labels:
        app: demo
        version: "1.0.0"
    spec:
      containers:
      - name: app
        image: nginx:1.25.5
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config
        configMap:
          name: app-v1-config